### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by atulmy** [google-github-actions/deploy-cloudrun#13]
### Question
Does Cloud Run does not support websockets? And is there any plan in future to support it?

**Comment by atulmy** [comment]
More info: https://issuetracker.google.com/issues/138440746

**Comment by steren** [comment]
This is out of scope of this repo. Please follow up on https://b.corp.google.com/issues/138440746

**Comment by atulmy** [comment]
FYI: Cloud Run now support WebSockets (since Jan 21, 2021)

https://cloud.google.com/blog/products/serverless/cloud-run-gets-websockets-http-2-and-grpc-bidirectional-streams
