### ISSUE TITLE
Existing env-variables are not being deleted

### ISSUE THREAD

**Issue by Villa41** [google-github-actions/deploy-cloudrun#184]
I have changed a sensitive value from "env-variable" to "secrets" with the same name. something like this:

Before
`env_vars: DB_URL=${{env.my-dummy-var}}`
After
`secrets: DB_URL=my-dummy-secret`

When the deploy was running "updates" were execute to change those properties so I got this error: 

`ERROR: (gcloud.beta.run.deploy) Cannot update environment variable [DB_URL] to the given type because it has already been set with a different type. `

And this is because the existing variable is not being deleted in cloud run, to solve this I needed to manually delete it in Cloud Run. 
The real problem is to execute automatic deployments when changes like this.

**Comment by averikitsch** [comment]
Unfortunately, this is not a use case we would recommend. The action should not change the underlying config without your knowledge. We recommend deleting the env var via the command line.
