### ISSUE TITLE
New revision isn't actually deployed

### ISSUE THREAD

**Issue by samos123** [google-github-actions/deploy-cloudrun#23]
The github action reports success however when I go to cloud run revision console it shows the latest deployed revision was from a week ago even though the github action ran today. The only way I can get the GH action to work again is to manually deploy a new revision from Cloud Run UI and then run the GH action again. That will work. However then any subsequent GH action won't result in new revision being deployment.

I highly suspect the logic with revision naming is causing issues. This might be the code that's causing the behaviour: https://github.com/google-github-actions/deploy-cloudrun/blob/main/src/cloudRun.ts#L194

This is the GH action example where it reported success but didn't actually deploy a new revision: https://github.com/websu-io/websu/runs/1693522408?check_suite_focus=true

Happy to show it through screenshare as well

**Comment by averikitsch** [comment]
Thanks for submitting, this looks similar to issue #12.

**Comment by samos123** [comment]
How can I easily try out your pull request to verify that it fixes the issue?

**Comment by averikitsch** [comment]
> How can I easily try out your pull request to verify that it fixes the issue?

That can be a little complicated with the repo setup. The PR doesn't include the compiled code - that gets built on PR merge. I did add tests for the use case to ensure revisions are being created. 

However, I pushed a branch with the compiled code which can be referenced in your workflow:
```
uses: google-github-actions/deploy-cloudrun@revision-test
```

Let me know if you have any issues.

**Comment by averikitsch** [comment]
Now available in `v0.3.0`.
