### ISSUE TITLE
Set timeout

### ISSUE THREAD

**Issue by Eomm** [google-github-actions/deploy-cloudrun#239]
### Question

How could you set the [timeout option](https://cloud.google.com/sdk/gcloud/reference/beta/run/deploy#--timeout)?

These two tries did not work: it is always 10 minutes:

```diff
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME }}
          region: ${{ secrets.GCP_CLOUDRUN_SERVICE_REGION }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
-          flags: --allow-unauthenticated --timeout=1800
-          flags: --allow-unauthenticated --timeout=30m
          source: .
```

<details>
  <summary>Click to expand!</summary>

![image](https://user-images.githubusercontent.com/11404065/136440296-52e95653-c916-4637-aaa3-1044f4b891f5.png)

</details>

**Comment by ciriousjoker** [comment]
Why was this closed? I still get the exact same behavior. Cloud build always has the default 10 minute timeout, even though the 30 minute timeout that I actually want gets passed to the gcloud run deploy command like this:

`gcloud beta run deploy service-name --quiet --platform managed --region europe-west3 --source ./ --timeout 30m --timeout 30m --project project-name --format json`

For some reason, the timeout is in there twice and in the "this is equivalent" notice there's no timeout at all:
> This command is equivalent to running `gcloud builds submit --tag [IMAGE] ./` and `gcloud run deploy web-frontend --image [IMAGE]`

(this might be expected though)

That being said, I'm new to this so perhaps I'm missing something...

**Comment by sethvargo** [comment]
Hi @ciriousjoker 

`--timeout` is the request execution timeout, not the build timeout. There is no way to set the build timeout: https://cloud.google.com/sdk/gcloud/reference/alpha/run/deploy#--timeout
