### ISSUE TITLE
How do you provide the filepath to the `metadata`

### ISSUE THREAD

**Issue by codeBehindMe** [google-github-actions/deploy-cloudrun#247]
### Question
So I'm not sure what i'm doing wrong here. But I keep a ```running: gcloud beta run services replace service.yaml --platform managed --region australia-southeast1
Error: ERROR: (gcloud.beta.run.services.replace) argument FILE: Failed to load YAML from [service.yaml]: Unable to read file [service.yaml]: [Errno 2] No such file or directory: 'service.yaml'``` error. 

I have copied the `service.yaml` file to every single possible location. relative to the directory path. i.e.
it is now at root of the repo; it is also at the `.github` folder. it's also at the `.github/workflows` folder. It is also at the `repo_root/infrac/service.yaml` location.

**Comment by sethvargo** [comment]
The `GITHUB_WORKSPACE` [environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) will point to the workspace directory path. Initially this is empty, until you run `actions/checkout`. Depending on your setup, this could be a different directory than the current working directory. So if the `service.yaml` is in your repo, you could specify the absolute path to avoid needing to find the relative location:

```text
gcloud beta run services replace $GITHUB_WORKSPACE/service.yaml ...
```

**Comment by erikw** [comment]
I get the same error as @codeBehindMe i.e.

```
running: gcloud beta run services replace /service.yaml --platform managed --region us-central1
Error: ERROR: (gcloud.beta.run.services.replace) argument FILE: Failed to load YAML from [/service.yaml]: Unable to read file [/service.yaml]: [Errno 2] No such file or directory: '/service.yaml'
Usage: gcloud beta run services replace FILE [optional flags]
```

Workflow-snippet:
```yaml
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        #metadata: service.yaml
        #metadata: ./service.yaml
        metadata: '${{ env.GITHUB_WORKSPACE }}/service.yaml'
```

I've tried, as seen, with metadata being just the filename, as well as @sethvargo's suggestion on using the `$GITHUB_WORKSPACE` envvar from actions/checkout.

**Comment by erikw** [comment]
@codeBehindMe I came here as I had the same issue. For me I turned out that debugging that I had disabled the `actions/checkout` step, thus the repo and the `service.yaml` was not available. This could maybe be the case for you as well?

**Comment by averikitsch** [comment]
use the metadata input with the relative path to the file, ex:
https://github.com/google-github-actions/deploy-cloudrun/blob/07a7b6c4efab20a52aa35710084ce16bb70a7d3b/.github/workflows/deploy-cloudrun-it.yml#L183
