### ISSUE TITLE
Labels in flags wont work due to below logic 

### ISSUE THREAD

**Issue by charan-doxel** [google-github-actions/deploy-cloudrun#258]
https://github.com/google-github-actions/deploy-cloudrun/blob/92e1db9e55efcb6ddc60ef91a3e948938a97b94e/src/deploy-cloudrun.ts#L239

**Comment by ralvarez-globant** [comment]
Hacky way to overcome this issue:
...
    - name: Prepare label
      shell: bash
      run: echo -e "--labels:\n  \"commit\": \"${{ github.event.workflow_run.head_sha }}\"\n  \"build_id\": \"${{github.event.workflow_run.id }}\"\n  \"deploy_id\": \"${{ github.run_id }}\"" >> labels.yml

    - name: Deploy
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        flags: ... --flags-file=labels.yml ...
        ...

**Comment by charan-doxel** [comment]
Thank you 👯‍♂️  it works. i missed using flags-file.
