### ISSUE TITLE
CLI instruction to create the appropriate minimal service account

### ISSUE THREAD

**Issue by louis030195** [google-github-actions/deploy-cloudrun#274]
### TL;DR

CLI instruction to create the appropriate minimal service account. 
e.g. 
```
gcloud create service account ...
gcloud give role service account ...
```

**Comment by sethvargo** [comment]
Hi @louis030195 - are you asking how to create a service account to use for deploying with Cloud Run, or are you asking about assigning a specific [service identity](https://cloud.google.com/run/docs/securing/service-identity) to a Cloud Run service.

**Comment by louis030195** [comment]
> Hi @louis030195 - are you asking how to create a service account to use for deploying with Cloud Run, or are you asking about assigning a specific [service identity](https://cloud.google.com/run/docs/securing/service-identity) to a Cloud Run service.

Oops, I mean for "create a service account to use for deploying with Cloud Run" not using service identity

**Comment by sethvargo** [comment]
```shell
gcloud iam service-accounts create "my-account"
```

```shell
gcloud projects add-iam-policy-binding "my-project" \
  --member="my-account@my-project.iam.gserviceaccount.com" \
  --role="roles/run.admin"
```
