### ISSUE TITLE
Switch to machine-parsable output

### ISSUE THREAD

**Issue by sethvargo** [google-github-actions/deploy-cloudrun#280]
### TL;DR

Currently, we rely on parsing the text output from the gcloud command to extract the URL and other outputs. This isn't guaranteed to be stable. We should instead use `--format=json` and parse the resulting output as JSON to extract desired values. This also would enable use to expose more outputs about the revision that we currently do not.

### Detailed design

```markdown
Append `--format=json` to all gcloud commands, parse output as JSON.
```

**Comment by verbanicm** [comment]
I am going to take a crack at this....
