### ISSUE TITLE
Example workflow links in README.md don't work

### ISSUE THREAD

**Issue by opheliagame** [google-github-actions/deploy-cloudrun#359]
I have been trying to figure out how to first build a docker image and then deploy it. There is a link for a sample workflow mentioned in the README.md file but it seems to be broken. Does it refer to any of the examples already present in the `.github/workflows` folder or am I looking in the wrong place?

**Comment by averikitsch** [comment]
Thanks for your report. I will update the README. You can find the example workflows now at https://github.com/google-github-actions/example-workflows. 
* [Deploy from source](https://github.com/google-github-actions/example-workflows/blob/main/workflows/deploy-cloudrun/cloudrun-source.yml)
* [Build and deploy](https://github.com/google-github-actions/example-workflows/blob/main/workflows/deploy-cloudrun/cloudrun-docker.yml)
