### ISSUE TITLE
Cloud Run jobs support

### ISSUE THREAD

**Issue by vh** [google-github-actions/deploy-cloudrun#364]
### TL;DR

Allow to deploy Cloud Run jobs.

**Comment by steveoh** [comment]
I would really enjoy this feature!

**Comment by misha130** [comment]
Anyone doing this? I am thinking of forking

**Comment by cloudmatt** [comment]
I'm assuming this hasn't/isn't being picked up? This would be super helpful for my workflows as well.

**Comment by spencercorwin** [comment]
Just made a PR for this as I really wanted it for my own workflow: #422

**Comment by misha130** [comment]
> Anyone doing this? I am thinking of forking

I simply ended up using cli to do this instead of this github action

```- name: 'Deploy cloud run job'
        run: |-
          gcloud --quiet beta run jobs update ${{ env.SERVICE }} \
          --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} \
          --max-retries	3 \
          --add-cloudsql-instances=.... \
          --vpc-connector=my-vpc-connector \
          --region some-region \
          --set-env-vars="...."

```

**Comment by steveoh** [comment]
@misha130 That will fail on the first run no? And don't you need to switch between --set and --update-env-vars based on if you are creating or updating?

**Comment by misha130** [comment]
> @misha130 That will fail on the first run no? And don't you need to switch between --set and --update-env-vars based on if you are creating or updating?

It's true, I create the job manually before deploying with a random image

**Comment by steveoh** [comment]
@misha130 Here's some code that will work for both. It'd be nice to have it all wrapped and managed by google's actions though. 

https://github.com/agrc/dhhs-cooling-towers/blob/dev/.github/workflows/release.yml#L88-L112

**Comment by JorritSalverda** [comment]
It seems the gcloud command to deploy a job is no longer in beta: https://cloud.google.com/sdk/gcloud/reference/run/jobs/create. So if that's what's holding things back it should get some traction again :)

**Comment by TheodorRene** [comment]
Got stumped on this today. Hoping for support one day 👍

**Comment by GusPrice** [comment]
Would love to see this get implemented, the work around in our pipelines is nasty :/

**Comment by jetaggart** [comment]
Is there documentation for this?
