### ISSUE TITLE
Would the maintainers be interested in having a cloud-scheduler action?

### ISSUE THREAD

**Issue by cpanato** [google-github-actions/deploy-cloudrun#405]
### TL;DR

I did not know where to open this issue and thought maybe here :)

I would like to ask if the maintainers are interested to have a cloud scheduler action?
if yes i can help to setup that.

thanks
cc @sethvargo

**Comment by sethvargo** [comment]
Hi @cpanato 

What would be the use case over `gcloud scheduler jobs runs`?

**Comment by cpanato** [comment]
more to hook up with the cloud run or functions to trigger, I was setting up a pipeline to deploy a cloud run and needed a cloud scheduler as well, but maybe we can just use the gcloud command and not over complicated 😅

**Comment by sethvargo** [comment]
I see - so you mean _creating_ a Cloud Scheduler job instead of invoking it? I'm not sure that's a good use case since IaC would probably be a better fit there.

**Comment by cpanato** [comment]
not a problem :) will close 
thanks for the quick reply
