### ISSUE TITLE
Different `flags` inputs for `deploy` and `update-traffic` commands

### ISSUE THREAD

**Issue by mrkstwrt** [google-github-actions/deploy-cloudrun#415]
### TL;DR

When passing `flags` input they are passed on to both `deploy` and `update-traffic` commands, this is problematic because for example you can't pass `--min-instances` if you're also passing an input like `tag_traffic` because it will error out with `unrecognized arguments` when it tries to call `update-traffic` with the same flag.

**Comment by sethvargo** [comment]
Hi @mrkstwrt - this is working as intended. `flags` is an advanced option, and we do not parse or validate the flags. I just updated the documentation in 4a1d803.
