### ISSUE TITLE
Add ability to force latest revision

### ISSUE THREAD

**Issue by samos123** [google-github-actions/deploy-cloudrun#46]
I manually changed traffic rules and afterwards the action won't automatically deploy new revisions to be the latest serving revision. The CLI has a command to automatically make latest the serving revision, it would be great if there was a parameter for the github action called `force_latest` that would force the latest revision to be the serving revisios by using this command:
```
gcloud run services update-traffic [[SERVICE] --to-latest
```

**Comment by aurecchia** [comment]
I was looking at the implementation, to add this feature, but from what I saw, think it should already be possible to manage the traffic of the latest revision, as far as I understand.

If either of the `revision_traffic` or `tag_traffic` options is set, the code [builds a base command](https://github.com/google-github-actions/deploy-cloudrun/blob/4fa10c38474c38d912f38753ccd1486a7b5e4fbd/src/main.ts#L102-L120) similar to the one suggested by @samos123.
Then, in the [documentation of `gcloud`](https://cloud.google.com/sdk/gcloud/reference/run/services/update-traffic) it is stated that one can always refer to the latest revision with `LATEST`.

Setting `revision_traffic` to `LATEST=100` should do the trick (though I have not checked it myself, yet)

**Comment by sethvargo** [comment]
Hi @aurecchia 

Yes - that's correct, and that's what gcloud does too. `--to-latest` is just syntactic sugar.

**Comment by rubiagatra** [comment]
should be close the issue then?
