### ISSUE TITLE
Docs on handling secrets with colons

### ISSUE THREAD

**Issue by nick-youngblut** [google-github-actions/deploy-cloudrun#471]
### TL;DR

I'm using an GitHub secret with an API key that contains a colon. 

This results in an `Invalid secret spec '***:latest'` error when trying to use the secret via:

```
          secrets: |
            API_KEY=${{ secrets.API_KEY }}:latest
```

While this might be a general GitHub Actions issue, it would be helpful to include docs in the README on how to deal with secrets that include a colon.

For instance, should one use single or double quotes around `${{ secrets.API_KEY }}` or `${{ secrets.API_KEY }}:latest`, or do something else?

**Comment by nick-youngblut** [comment]
Never mind. I believe that I misunderstood the syntax of `secrets:`

**Comment by melyux** [comment]
@nick-youngblut How'd you misunderstand the syntax? I'm running into a similar issue

**Comment by nick-youngblut** [comment]
@melyux an example of how I set secrets for deploying on Cloud Run:

```yaml
      - id: "Deploy"
        name: "Deploy to Cloud Run"
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: "${{ env.APP }}"
          image: "us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
          region: "us-west1"
          secrets: |
            BENCHLING_DEV_DB_PASSWORD=BENCHLING_DEV_DB_PASSWORD:latest
            BENCHLING_PROD_DB_PASSWORD=BENCHLING_PROD_DB_PASSWORD:latest
          flags: >
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }}
            --set-env-vars=R_CONFIG_ACTIVE=${{ env.R_CONFIG_ACTIVE }}
            --port=8080
            --cpu=2
            --memory=2Gi
            --min-instances=0
            --max-instances=1
            --concurrency=80
```

The `BENCHLING_DEV_DB_PASSWORD` and `BENCHLING_PROD_DB_PASSWORD` secrets are stored in the GCP Secret Manager.

**Comment by melyux** [comment]
Thanks @nick-youngblut. I had assumed deploy would let us set the secret values themselves for the run, but this apparently isn't the case. Not clear from the documentation

**Comment by nick-youngblut** [comment]
Yeah, the docs are not very clear. GPT-4o can help, but it does get some stuff wrong.
