### ISSUE TITLE
Display Cloud Run instance logs of failed deploys

### ISSUE THREAD

**Issue by FabianFrank** [google-github-actions/deploy-cloudrun#493]
### TL;DR

When a deploy fails this action should pull the logs of the new instance that failed to boot and echo the log so that it is available in the GitHub actions logs without having to go to cloud run logs.

**Comment by sethvargo** [comment]
Hi @FabianFrank unfortunately this isn't feasible, as it would require extra permissions. Additionally, we rely on `gcloud` under the hood to deploy these containers, so gcloud would need to add this feature.
