### ISSUE TITLE
ENV var key value paring in 2.3.0 critical bug

### ISSUE THREAD

**Issue by scottravio** [google-github-actions/deploy-cloudrun#503]
### TL;DR

bug introduced here: https://github.com/google-github-actions/deploy-cloudrun/pull/496

The KV parser creates a delimiter string which does not exist in the input string. This can cause an error when an env var value ends with the start of the delim string.

For instance, if a delim string is `dd` and I have an ENV var SOMETHING=hello-world SOMETHING_ELSE=foo, the string ends up like `SOMETHING=hello-worldddSOMETHING_ELSE=foo`, which creates cloud run ENV variables:
```
SOMETHING=hello-worl
dSOMETHING_ELSE=foo
```

### Expected behavior

ENV variables correctly parsed

### Action YAML

```yaml
N/A
```

**Comment by njhartwell** [comment]
This is still an issue in the (presumably uncommon, but still possible case) where concatenating the value and delimiter results produces a new occurrence of the delimiter. 

e.g. for the label `commit-sha=xxxx524` and the delimiter `5245`

`^5245^commit-sha=xxxx5245245ref-name=main`

yields `245ref-name=main`
